
// GET BLOGS ACTION //
export const GET_BLOG_PROGRESS = "GET_BLOG_PROGRESS"
export const GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS"
export const GET_BLOG_ERROR = "GET_BLOG_ERROR"

// DELETE BLOGS ACTION //
export const DELETE_BLOG_PROGRESS = "DELETE_BLOG_PROGRESS"
export const DELETE_BLOG_SUCCESS = "GET_BLOG_SUCCESS"
export const DELETE_BLOG_ERROR = "DELETE_BLOG_ERROR"

// USER BLOGS ACTION //
export const USER_BLOG_PROGRESS = "USER_BLOG_PROGRESS"
export const USER_BLOG_SUCCESS = "USER_BLOG_SUCCESS"
export const USER_BLOG_ERROR = "USER_BLOG_ERROR"


